org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# ---------------------------------------------------------------
# کلیدهای ادیوری
# ---------------------------------------------------------------
ADIVERY_APP_ID=9909ca36-2f9a-4f8c-bfe7-ef81a95f0183
ADIVERY_PLACEMENT_INTERSTITIAL=f363e037-6c94-4c44-9003-32f513b70891
ADIVERY_PLACEMENT_BANNER=486bdbd7-451a-485f-8f49-6fbc7b22169a
